# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170702_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_contacted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
